function h = makeniihdr(varargin)
% function h = makeniihdr(varargin)
%
% Part of fmrifrey/mri-devtools software package by David Frey (2023)
%   git@github.com:fmrifrey/mri-devtools.git
%
% Description: Function to make nii header
%
%
% Notes: 
%   - variable input arguments mirror nii header structure fields, for more
%       info: https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h
%   - most fields will already be filled in with good defaults
%   - this function is intended to be called by other scripts, not users
%
% Function output:
%   - h:
%       - nifti header structure
%

    % Define empty (default) header
    h_empty = struct (...
        'sizeof_hdr',       348, ...
        'data_type',        char(zeros(10,1)),...
        'db_name',          char(zeros(18,1)),...
        'extents',          0, ...
        'session_error',    0, ...
        'regular',          'r', ...
        'dim_info',         char(zeros(1,1)), ...
        'dim',              zeros(8,1), ...
        'intent_p1',        0, ... 
        'intent_p2',        0, ...
        'intent_p3',        0, ...
        'intent_code',      0, ...
        'datatype',         0, ...
        'bitpix',           0, ...
        'slice_start',      0, ...
        'pixdim',           zeros(8,1), ...
        'vox_offset',       352, ...
        'scl_slope',        1, ...
        'scl_inter',        0, ...
        'slice_end',        0, ...
        'slice_code',       char(zeros(1,1)), ...
        'xyzt_units',       char(zeros(1,1)), ...
        'cal_max',          0, ...
        'cal_min',          0, ...
        'slice_duration',   0, ...
        'toffset',          0, ...
        'glmax',            0, ...
        'glmin',            0, ...
        'descrip',          char(zeros(80,1)), ...
        'aux_file',         char(zeros(24,1)), ...
        'qform_code',       0, ...
        'sform_code',       0, ...
        'quatern_b',        0, ...
        'quatern_c',        0, ...
        'quatern_d',        0, ...
        'qoffset_x',        0, ...
        'qoffset_y',        0, ...
        'qoffset_z',        0, ...
        'srow_x',           zeros(4,1), ...
        'srow_y',           zeros(4,1), ...
        'srow_z',           zeros(4,1), ...
        'intent_name',      char(zeros(16,1)), ...
        'magic',            sprintf('%s\0','n+1') , ...
        'originator',       zeros(5,1),...
        'esize',            0, ...
        'ecode',            0, ...
        'edata',            '' ...
    );
    
    % Parse through variable inputs using matlab's built-in input parser
    h = vararginparser(h_empty,varargin{:});

end

